### ISSUE TITLE
Multiple activation with repeatable triggers

### ISSUE THREAD

**Issue by peroxside** [ahoys/Actionbuilder#55]
When using an Actionpoint with a repeatable trigger the Actionpoint fires both on activation and deactivation of the trigger.

How to replicate:
- place an Actionpoint module, a Portal module and a group
- sync AP -> Portal -> Group
- add a trigger and sync it to the Actionpoint
- set the trigger to Anyplayer present repeatable
- walk in the trigger to spawn the units
- walk out of the trigger, every unit is now doubled

Version: current Steam Workshop version (2018/02/20)
Intended Use: Respawning enemy bases

Comment:
If this would be fixed one wouldn't need the 3 trigger workaround as seen in the examples.
Nonetheless Actionbuilder is really remarkable and has changed the way I create missions! Amazing work!

**Comment by ahoys** [comment]
You should use Repeater module for multiple activations.

The reason why AB modules trigger from both activation and deactivation of Arma triggers, is that it is actually the state change of the trigger that causes the triggering. Tools for monitoring trigger state changes are quite limited. This is why I had to create my own "repeatable triggers"; the Repeater module.

I'm closing this for now, as the whole problem can be circumvented with Repeater modules.

[Actionbuilder Repeater Examples](https://github.com/ahoys/Actionbuilder/blob/master/docs/Actionbuilder%20Repeater%20Examples%201.3.x.pdf)

**Comment by peroxside** [comment]
Thank you for your reply and explanation.

I found another workaround for now as using the Repeater Module didn't yield the results I wanted. My problem was that, while triggering the Repeater Module with a trigger worked great, I couldn't stop the Action Point from triggering at the beginning of the game which resulted in one group always being present instead of when the player entered the trigger area.

Could you maybe add a Checkbox to the Repeater Module that prevents the Actionpoint from activating initially?

My current workaround consists of a doubled trigger, one set to present, one to not present. The "present" one activates the AP and the "not present" one activates a priority waypoint "remove group". This way both the group that spawns on entering as well as the group than spawns on retriggering when leaving are despawned by this waypoint.
This is the only solution I found which does not need additional variables. As I intend to use this in large scale missions I didn't want to create lots of variables for each of these areas.

Anyway, thanks for taking the time to answer and explain this to me. Looking forward to future updates,

**Comment by ahoys** [comment]
Did you try to prevent the Actionpoint itself from being triggered, initially? The repeater should start repeating only after the synchronized Actionpoint has triggered at least once. It shouldn't be able to launch the 1st spawn.

**Comment by peroxside** [comment]
Thank you! Now it works as expected. I can't believe I missed that... so sorry to bother you
